
components:
  - name: argocd
    images:
      - docker.io/library/redis:8.2.3-alpine
      - quay.io/argoproj/argocd:v3.3.2
      # Cosign artifacts for images - argocd
      - quay.io/argoproj/argocd:sha256-5882f28f7aaeaac397949c4511fdc1ad66c1260af44166ccf7e57aca3d7b9797.att

